No change history kept

diff --git a/build_vivado b/build_vivado
--- a/build_vivado
+++ b/build_vivado
@@ -234,13 +234,13 @@ update_timestamp_file()
 
 
 #==================================================================
-# This function removes every runme.log it finds
+# This function removes every .log it finds
 #==================================================================
-remove_runme_logs()
+remove_logs()
 {
-    find . | grep "runme\.log$" >log_list
+    find . | grep "\.log$" >log_list
     while IFS= read line; do
-            rm -rf $line
+        rm -rf $line
     done < log_list
     rm log_list
 }
@@ -372,6 +372,9 @@ copy_build_artifacts()
     test -z $binfile || cp $binfile $dest/${project_name}.bin
     test -z $ltxfile || cp $ltxfile $dest/${project_name}.ltx
 
+    # If fpga_regs.h exists, copy it to the destination directory
+    test -f fpga_regs.h && cp fpga_regs.h >$dest/git_hash
+
     # Create an artifact file that contains the git hash
     echo $(get_commit_hash) > $dest/git_hash
 }
@@ -422,7 +425,7 @@ project="${project_file%.*}"
 rm -rf ${project}.runs/impl_1/*
 
 # Make sure the log files don't exist
-remove_runme_logs
+remove_logs
 
 # This timestamp will be used to name the build artifact folder
 # and will also be written into the bitstream file
@@ -451,12 +454,26 @@ while true; do
    sleep 2
 done
 
-# If the build was successful, copy the artifacts
-if [ $(cat build.result) == "pass" ]; then
-    copy_build_artifacts $artifact_folder
-    post_build="./post_build.sh"
-    if [ -f $post_build ]; then
-        chmod +x $post_build
-        $post_build $artifact_folder
-    fi
+
+# If the build failed, we're done
+if [ $(cat build.result) == "fail" ]; then
+    exit 1
+fi
+
+#------------------------------------------
+# If we get here, the build was successful
+#------------------------------------------
+if [ -f make_fpga_regs ]; then
+    chmod +x make_fpga_regs
+    ./make_fpga_regs
+fi
+
+# Copy the build artifacts
+copy_build_artifacts $artifact_folder
+
+# If there is a post-build step, run it
+post_build="./post_build.sh"
+if [ -f $post_build ]; then
+    chmod +x $post_build
+    $post_build $artifact_folder
 fi
