No change history kept

diff --git a/update_git_hash_vh b/update_git_hash_vh
--- a/update_git_hash_vh
+++ b/update_git_hash_vh
@@ -21,6 +21,9 @@ update_githash_file()
     # We don't have a fully qualified path to our updateable file yet
     local fqp=
 
+    # This is the basename of the file we're going to update
+    local ofile=git_hash
+
     # Sit in a loop and parse the command line options
     while [ ! -z $1 ]; do
 
@@ -32,6 +35,7 @@ update_githash_file()
             continue
         fi
 
+        # Did the caller hand us a directory name on the command line?
         if [ "$1" == "--dir" ]; then
             local dir=$2
             if [ -z $dir ] || [ ! -d $dir ]; then 
@@ -44,16 +48,12 @@ update_githash_file()
             continue
         fi
 
+        # If we get here, the caller screwed up
         echo "Unknown option $1" 1>&2
         return 4
 
     done
 
-    # This is the basename of the file we're going to update
-    local ofile=git_hash
-
-    # We don't have a fully qualified path for our updateable file yet
-    local fqp=
 
     # If the current directory isn't a git repo, complain and quit
     if [ ! -d .git ]; then
@@ -70,7 +70,7 @@ update_githash_file()
 
     # If we couldn't find a hash-file, complain
     if [ -z $fqp ]; then
-        echo "Couldn't find ${ofile}.vh!" 1>&2
+        echo "${ofile}.vh not found under $PWD !" 1>&2
         return 2
     fi
 
