No change history kept

diff --git a/update_git_hash_vh b/update_git_hash_vh
--- a/update_git_hash_vh
+++ b/update_git_hash_vh
@@ -7,25 +7,57 @@
 # "git_hash.vh" file, so the Vivado IPI won't erroneously complain
 # that we have updated a module.
 #
-# If you pass this function a value, that value will be used as
-# the hash (instead of the hash of the most recent commit)
+# Function options:
+#  --dir <working_directory_name>
+#  --hash <string_of_hex>
 #
 # Doug Wolf wrote this
 #==================================================================
 update_githash_file()
 {
+    # We don't know what our hash is yet
+    local hash=
+    
+    # We don't have a fully qualified path to our updateable file yet
+    local fqp=
+
+    # Sit in a loop and parse the command line options
+    while [ ! -z $1 ]; do
+
+        # Did the caller hand us a hash on the command line?
+        if [ "$1" == "--hash" ]; then
+            hash=$2
+            shift
+            shift
+            continue
+        fi
+
+        if [ "$1" == "--dir" ]; then
+            local dir=$2
+            if [ -z $dir ] || [ ! -d $dir ]; then 
+                echo "$dir not found!" 1>&2
+                return 3
+            fi
+            cd $dir
+            shift
+            shift
+            continue
+        fi
+
+        echo "Unknown option $1" 1>&2
+        return 4
+
+    done
+
     # This is the basename of the file we're going to update
     local ofile=git_hash
 
-    # We don't have a fully qualified path for our output file yet
+    # We don't have a fully qualified path for our updateable file yet
     local fqp=
-
-    # The caller may have passed us a hash
-    local hash=$1
 
     # If the current directory isn't a git repo, complain and quit
     if [ ! -d .git ]; then
-        echo "This is not a git repo!" 1>&2
+        echo "$PWD is not a git repo!" 1>&2
         return 1
     fi
 
@@ -64,6 +96,6 @@ update_githash_file()
 }
 #==================================================================
 
-update_githash_file $1
+update_githash_file $1 $2 $3 $4 $5 $6 $7 $8 $9
 
 
