No change history kept

diff --git a/update_git_hash_vh b/update_git_hash_vh
--- a/update_git_hash_vh
+++ b/update_git_hash_vh
@@ -38,7 +38,7 @@ update_githash_file()
 
     # If we couldn't find a hash-file, complain
     if [ -z $fqp ]; then
-        echo "Couldn't find ${ofile}.vh!"
+        echo "Couldn't find ${ofile}.vh!" 1>&2
         return 2
     fi
 
